<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Guna.UI2.WinForms" Version="2.0.4.8" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.1" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.8" />
    <PackageReference Include="System.Data.SqlClient" Version="4.9.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Application\Application.csproj" />
    <ProjectReference Include="..\Domain\Domain.csproj" />
    <ProjectReference Include="..\Infracstructure\Infracstructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="FrmDangKy_1.cs" />
    <Compile Update="FrmDangKy_2.cs" />
    <Compile Update="FrmDangNhap.cs" />
    <Compile Update="FrmMain.cs" />
    <Compile Update="FrmQuenMatKhau_1.cs" />
    <Compile Update="FrmQuenMatKhau_2.cs" />
    <Compile Update="FrmXacNhanMa.cs" />
    <Compile Update="FrmXacThucMaMK.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Update="App.config">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>